[build]
  command = "npm run build"
  publish = "dist"   # <-- sesuaikan dengan folder hasil build kamu (Vite biasanya "dist", CRA biasanya "build")

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
