export const BaseJadwal = {
  trainer_id: "",
  fullname: "",
  gender: "",
  kolam: [],
  total_order: 0,
  percent: 0,
  datahari: [
    {
      hari: "Senin",
      data: [
        {
          jam: "06.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "07.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "08.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "09.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "10.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "11.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "12.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "13.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "14.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "15.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "16.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "17.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "18.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "19.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
      ],
    },
    {
      hari: "Selasa",
      data: [
        {
          jam: "06.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "07.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "08.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "09.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "10.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "11.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "12.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "13.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "14.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "15.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "16.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "17.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "18.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "19.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
      ],
    },
    {
      hari: "Rabu",
      data: [
        {
          jam: "06.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "07.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "08.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "09.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "10.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "11.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "12.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "13.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "14.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "15.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "16.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "17.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "18.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "19.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
      ],
    },
    {
      hari: "Kamis",
      data: [
        {
          jam: "06.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "07.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "08.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "09.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "10.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "11.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "12.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "13.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "14.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "15.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "16.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "17.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "18.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "19.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
      ],
    },
    {
      hari: "Jumat",
      data: [
        {
          jam: "06.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "07.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "08.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "09.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "10.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "11.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "12.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "13.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "14.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "15.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "16.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "17.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "18.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "19.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
      ],
    },
    {
      hari: "Sabtu",
      data: [
        {
          jam: "06.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "07.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "08.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "09.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "10.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "11.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "12.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "13.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "14.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "15.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "16.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "17.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "18.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "19.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
      ],
    },
    {
      hari: "Minggu",
      data: [
        {
          jam: "06.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "07.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "08.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "09.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "10.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "11.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "12.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "13.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "14.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "15.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "16.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "17.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "18.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
        {
          jam: "19.00",
          orders: [
            {
              is_free: false,
              order_id: "",
              student: [],
              product: "",
              pool_name: "",
              p: [
                { meet: 1, tgl: "" },
                { meet: 2, tgl: "" },
                { meet: 3, tgl: "" },
                { meet: 4, tgl: "" },
                { meet: 5, tgl: "" },
                { meet: 6, tgl: "" },
                { meet: 7, tgl: "" },
                { meet: 8, tgl: "" },
              ],
            },
          ],
        },
      ],
    },
  ],
};
