export const BaseJadwal = {
  trainer_id: "",
  fullname: "",
  gender: "",
  kolam: [],
  datahari: [
    {
      hari: "Senin",
      data: [
        {
          jam: "06.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "07.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "08.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "09.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "10.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "11.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "12.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "13.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "14.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "15.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "16.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "17.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "18.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "19.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
      ],
    },
    {
      hari: "Selasa",
      data: [
        {
          jam: "06.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "07.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "08.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "09.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "10.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "11.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "12.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "13.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "14.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "15.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "16.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "17.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "18.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "19.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
      ],
    },
    {
      hari: "Rabu",
      data: [
        {
          jam: "06.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "07.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "08.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "09.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "10.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "11.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "12.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "13.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "14.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "15.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "16.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "17.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "18.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "19.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
      ],
    },
    {
      hari: "Kamis",
      data: [
        {
          jam: "06.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "07.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "08.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "09.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "10.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "11.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "12.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "13.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "14.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "15.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "16.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "17.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "18.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "19.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
      ],
    },
    {
      hari: "Jumat",
      data: [
        {
          jam: "06.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "07.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "08.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "09.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "10.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "11.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "12.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "13.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "14.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "15.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "16.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "17.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "18.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "19.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
      ],
    },
    {
      hari: "Sabtu",
      data: [
        {
          jam: "06.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "07.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "08.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "09.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "10.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "11.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "12.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "13.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "14.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "15.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "16.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "17.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "18.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "19.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
      ],
    },
    {
      hari: "Minggu",
      data: [
        {
          jam: "06.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "07.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "08.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "09.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "10.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "11.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "12.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "13.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "14.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "15.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "16.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "17.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "18.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
        {
          jam: "19.00",
          is_free: false,
          order_id: "",
          student: [],
          product: "",
          pool_name: "",
        },
      ],
    },
  ],
};
